name: ers
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  url_launcher: ^5.4.2
  google_fonts: ^0.3.9
  cloud_firestore: 0.13.4+2

  shared_preferences: ^0.5.6+3
  data_connection_checker: ^0.3.4
  cached_network_image: ^2.0.0-rc
  google_nav_bar: ^2.0.1
  intl: ^0.16.1
  bubble: ^1.1.9+1
  http: ^0.12.0+4
  path_provider: ^1.6.5
  equatable: ^1.1.1
  google_maps_flutter: ^0.5.26
  hive: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
